//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtCQRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorseImages
    {
        public int Id { get; set; }
        public Nullable<int> HorseId { get; set; }
        public System.DateTime PublicationDate { get; set; }
        public string Caption { get; set; }
        public string Comment { get; set; }
        public bool IsMain { get; set; }
        public Nullable<int> UploadId { get; set; }
        public string OldSystemId { get; set; }
        public string OldSystemId2 { get; set; }
        public string VniikId { get; set; }
    
        public virtual Horses Horses { get; set; }
        public virtual Uploads Uploads { get; set; }
    }
}
