//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtCQRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Horses()
        {
            this.HorseFrisknessRecord = new HashSet<HorseFrisknessRecord>();
            this.HorseImages = new HashSet<HorseImages>();
            this.HorseMeasures = new HashSet<HorseMeasures>();
            this.HorseOwnHistory = new HashSet<HorseOwnHistory>();
            this.HorseRacetrackStats = new HashSet<HorseRacetrackStats>();
            this.Horses1 = new HashSet<Horses>();
            this.Horses11 = new HashSet<Horses>();
            this.RaceClaims = new HashSet<RaceClaims>();
            this.RaceResults = new HashSet<RaceResults>();
            this.RaceStartPosition = new HashSet<RaceStartPosition>();
            this.Uploads = new HashSet<Uploads>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string NameEng { get; set; }
        public System.DateTime BirthDate { get; set; }
        public System.DateTime DeathDate { get; set; }
        public string Blood { get; set; }
        public string BloodEng { get; set; }
        public string GbpNumber { get; set; }
        public string GbpNumberNew { get; set; }
        public string LifeNumber { get; set; }
        public string Brand { get; set; }
        public string Family { get; set; }
        public bool IsAncestor { get; set; }
        public string Comment { get; set; }
        public Nullable<int> FatherId { get; set; }
        public string FatherName { get; set; }
        public Nullable<int> MotherId { get; set; }
        public string MotherName { get; set; }
        public Nullable<int> HorseBreedId { get; set; }
        public Nullable<int> HorseColorId { get; set; }
        public Nullable<int> HorseClassId { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> BirthOwnerId { get; set; }
        public string OldSystemId { get; set; }
        public string OldSystemId2 { get; set; }
        public string VniikId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorseFrisknessRecord> HorseFrisknessRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorseImages> HorseImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorseMeasures> HorseMeasures { get; set; }
        public virtual HorseOwners HorseOwners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorseOwnHistory> HorseOwnHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorseRacetrackStats> HorseRacetrackStats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horses> Horses1 { get; set; }
        public virtual Horses Horses2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horses> Horses11 { get; set; }
        public virtual Horses Horses3 { get; set; }
        public virtual LookupGenders LookupGenders { get; set; }
        public virtual LookupHorseBreeds LookupHorseBreeds { get; set; }
        public virtual LookupHorseClasses LookupHorseClasses { get; set; }
        public virtual LookupHorseColors LookupHorseColors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaceClaims> RaceClaims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaceResults> RaceResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaceStartPosition> RaceStartPosition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uploads> Uploads { get; set; }
    }
}
