//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtCQRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorseOwnHistory
    {
        public int Id { get; set; }
        public System.DateTime OwnStartDate { get; set; }
        public Nullable<System.DateTime> OwnEndDate { get; set; }
        public Nullable<int> OwnTypeId { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public Nullable<int> HorseId { get; set; }
        public string OldSystemId { get; set; }
        public string OldSystemId2 { get; set; }
        public string VniikId { get; set; }
        public Nullable<int> CreateByAdminId { get; set; }
    
        public virtual HorseOwners HorseOwners { get; set; }
        public virtual Horses Horses { get; set; }
        public virtual LookupOwnershipTypes LookupOwnershipTypes { get; set; }
        public virtual RacetrackUsers RacetrackUsers { get; set; }
    }
}
