//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtCQRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorseRacetrackStats
    {
        public int Id { get; set; }
        public System.DateTime DateIn { get; set; }
        public Nullable<System.DateTime> DateOut { get; set; }
        public decimal RacetrackMoneyWin { get; set; }
        public decimal RacetrackPointsWin { get; set; }
        public Nullable<int> CoachId { get; set; }
        public Nullable<int> HorseId { get; set; }
        public Nullable<int> RacetrackId { get; set; }
        public string OldSystemId { get; set; }
        public string OldSystemId2 { get; set; }
        public string VniikId { get; set; }
        public bool IsGuest { get; set; }
    
        public virtual Horses Horses { get; set; }
        public virtual LookupRacetracks LookupRacetracks { get; set; }
        public virtual Riders Riders { get; set; }
    }
}
