//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtCQRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupRacetracks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LookupRacetracks()
        {
            this.HorseFrisknessRecord = new HashSet<HorseFrisknessRecord>();
            this.HorseMeasures = new HashSet<HorseMeasures>();
            this.HorseRacetrackStats = new HashSet<HorseRacetrackStats>();
            this.RaceCalendar = new HashSet<RaceCalendar>();
            this.RacetrackUsers = new HashSet<RacetrackUsers>();
            this.Riders = new HashSet<Riders>();
            this.Uploads = new HashSet<Uploads>();
        }
    
        public int Id { get; set; }
        public string City { get; set; }
        public string CityEng { get; set; }
        public Nullable<int> RacetrackClass { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Name { get; set; }
        public string NameEng { get; set; }
        public string Code { get; set; }
        public string OldSystemId { get; set; }
        public string OldSystemId2 { get; set; }
        public string VniikId { get; set; }
        public string Address { get; set; }
        public string ResourceId { get; set; }
        public string Contacts { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorseFrisknessRecord> HorseFrisknessRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorseMeasures> HorseMeasures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorseRacetrackStats> HorseRacetrackStats { get; set; }
        public virtual LookupCountries LookupCountries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaceCalendar> RaceCalendar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RacetrackUsers> RacetrackUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Riders> Riders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uploads> Uploads { get; set; }
    }
}
