//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtCQRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortalLog
    {
        public int Id { get; set; }
        public string LogDate { get; set; }
        public string LogLevel { get; set; }
        public string Application { get; set; }
        public string Message { get; set; }
        public string MethodInfo { get; set; }
        public string Exception { get; set; }
        public string AspNetIdentity { get; set; }
        public string RequestId { get; set; }
        public string EventId { get; set; }
        public string AspNetSessionId { get; set; }
        public string RequestedUrl { get; set; }
        public string RequestFrom { get; set; }
    }
}
