//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtCQRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prizes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prizes()
        {
            this.RaceCalendar = new HashSet<RaceCalendar>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string NameEng { get; set; }
        public string PrizeCategoryRu { get; set; }
        public string PrizeCategoryInternational { get; set; }
        public int TotalPoints { get; set; }
        public bool IsTraditional { get; set; }
        public Nullable<int> AgeCategoryId { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> DistanceId { get; set; }
        public Nullable<int> HorseBreedId { get; set; }
        public Nullable<int> JusticedId { get; set; }
        public string OldSystemId { get; set; }
        public string OldSystemId2 { get; set; }
        public string VniikId { get; set; }
        public int TotalMoney { get; set; }
        public string Comments { get; set; }
    
        public virtual LookupAgeCategories LookupAgeCategories { get; set; }
        public virtual LookupDistances LookupDistances { get; set; }
        public virtual LookupGenders LookupGenders { get; set; }
        public virtual LookupHorseBreeds LookupHorseBreeds { get; set; }
        public virtual LookupJusticeTypes LookupJusticeTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaceCalendar> RaceCalendar { get; set; }
    }
}
