//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtCQRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaceClaims
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RaceClaims()
        {
            this.RaceResults = new HashSet<RaceResults>();
        }
    
        public int Id { get; set; }
        public System.DateTime ClaimDate { get; set; }
        public bool IsClaimAccepted { get; set; }
        public string DeclineReason { get; set; }
        public bool IsPaymentCompleted { get; set; }
        public Nullable<int> RaceId { get; set; }
        public Nullable<int> HorseId { get; set; }
        public Nullable<int> RiderId { get; set; }
        public Nullable<int> CoachId { get; set; }
        public Nullable<int> OwnerId { get; set; }
    
        public virtual HorseOwners HorseOwners { get; set; }
        public virtual Horses Horses { get; set; }
        public virtual RaceCalendar RaceCalendar { get; set; }
        public virtual Riders Riders { get; set; }
        public virtual Riders Riders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaceResults> RaceResults { get; set; }
    }
}
