//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtCQRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RacetrackUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RacetrackUsers()
        {
            this.HorseOwnHistory = new HashSet<HorseOwnHistory>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string IdentityId { get; set; }
        public Nullable<int> HorseOwnerId { get; set; }
        public Nullable<int> RiderId { get; set; }
        public Nullable<int> AssignedRacetrackId { get; set; }
    
        public virtual HorseOwners HorseOwners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorseOwnHistory> HorseOwnHistory { get; set; }
        public virtual LookupRacetracks LookupRacetracks { get; set; }
        public virtual Riders Riders { get; set; }
    }
}
