//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtCQRS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RacetrackIASEntities : DbContext
    {
        public RacetrackIASEntities()
            : base("name=RacetrackIASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Documents> Documents { get; set; }
        public virtual DbSet<HorseFrisknessRecord> HorseFrisknessRecord { get; set; }
        public virtual DbSet<HorseImages> HorseImages { get; set; }
        public virtual DbSet<HorseMeasures> HorseMeasures { get; set; }
        public virtual DbSet<HorseOwners> HorseOwners { get; set; }
        public virtual DbSet<HorseOwnHistory> HorseOwnHistory { get; set; }
        public virtual DbSet<HorseRacetrackStats> HorseRacetrackStats { get; set; }
        public virtual DbSet<Horses> Horses { get; set; }
        public virtual DbSet<LookupAgeCategories> LookupAgeCategories { get; set; }
        public virtual DbSet<LookupCountries> LookupCountries { get; set; }
        public virtual DbSet<LookupCoverType> LookupCoverType { get; set; }
        public virtual DbSet<LookupCurrencies> LookupCurrencies { get; set; }
        public virtual DbSet<LookupDisciplines> LookupDisciplines { get; set; }
        public virtual DbSet<LookupDistances> LookupDistances { get; set; }
        public virtual DbSet<LookupGenders> LookupGenders { get; set; }
        public virtual DbSet<LookupHorseBodyCondition> LookupHorseBodyCondition { get; set; }
        public virtual DbSet<LookupHorseBreeds> LookupHorseBreeds { get; set; }
        public virtual DbSet<LookupHorseClasses> LookupHorseClasses { get; set; }
        public virtual DbSet<LookupHorseColors> LookupHorseColors { get; set; }
        public virtual DbSet<LookupJusticeTypes> LookupJusticeTypes { get; set; }
        public virtual DbSet<LookupOwnerChangeReasons> LookupOwnerChangeReasons { get; set; }
        public virtual DbSet<LookupOwnershipTypes> LookupOwnershipTypes { get; set; }
        public virtual DbSet<LookupPrizeMoneyDistributions> LookupPrizeMoneyDistributions { get; set; }
        public virtual DbSet<LookupRaceComplication> LookupRaceComplication { get; set; }
        public virtual DbSet<LookupRacePenalties> LookupRacePenalties { get; set; }
        public virtual DbSet<LookupRaceSubTypes> LookupRaceSubTypes { get; set; }
        public virtual DbSet<LookupRacetracks> LookupRacetracks { get; set; }
        public virtual DbSet<LookupRiderCategories> LookupRiderCategories { get; set; }
        public virtual DbSet<LookupRiderPositions> LookupRiderPositions { get; set; }
        public virtual DbSet<PortalLog> PortalLog { get; set; }
        public virtual DbSet<Posts> Posts { get; set; }
        public virtual DbSet<Prizes> Prizes { get; set; }
        public virtual DbSet<RaceCalendar> RaceCalendar { get; set; }
        public virtual DbSet<RaceClaims> RaceClaims { get; set; }
        public virtual DbSet<RaceGitResults> RaceGitResults { get; set; }
        public virtual DbSet<RaceResults> RaceResults { get; set; }
        public virtual DbSet<RaceStartPosition> RaceStartPosition { get; set; }
        public virtual DbSet<RacetrackPenalties> RacetrackPenalties { get; set; }
        public virtual DbSet<RacetrackUsers> RacetrackUsers { get; set; }
        public virtual DbSet<Riders> Riders { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<Uploads> Uploads { get; set; }
    }
}
