//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtCQRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaceCalendar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RaceCalendar()
        {
            this.RaceClaims = new HashSet<RaceClaims>();
            this.RaceResults = new HashSet<RaceResults>();
            this.RaceStartPosition = new HashSet<RaceStartPosition>();
        }
    
        public int Id { get; set; }
        public int DayRaceNum { get; set; }
        public int YearRaceNum { get; set; }
        public System.DateTime RaceDate { get; set; }
        public int GitCount { get; set; }
        public int ParticipantsCount { get; set; }
        public decimal PrizeMoney { get; set; }
        public decimal AdditionalMoney { get; set; }
        public int PrizePoints { get; set; }
        public decimal RaceTotalPrice { get; set; }
        public decimal RaceNominationPrice { get; set; }
        public decimal RaceStartPrice { get; set; }
        public Nullable<int> RaceTypeId { get; set; }
        public Nullable<int> MoneyDistributionId { get; set; }
        public Nullable<int> AgeCategoryId { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> HorseBreedId { get; set; }
        public Nullable<int> DistanceId { get; set; }
        public Nullable<int> RacetrackId { get; set; }
        public Nullable<int> CoverTypeId { get; set; }
        public Nullable<int> PrizeId { get; set; }
        public string OldSystemId { get; set; }
        public string OldSystemId2 { get; set; }
        public string VniikId { get; set; }
        public System.DateTime RegistrationStartDate { get; set; }
        public System.DateTime RegistrationFinishDate { get; set; }
        public Nullable<int> RaceSubTypeId { get; set; }
    
        public virtual LookupAgeCategories LookupAgeCategories { get; set; }
        public virtual LookupCoverType LookupCoverType { get; set; }
        public virtual LookupDistances LookupDistances { get; set; }
        public virtual LookupGenders LookupGenders { get; set; }
        public virtual LookupHorseBreeds LookupHorseBreeds { get; set; }
        public virtual LookupPrizeMoneyDistributions LookupPrizeMoneyDistributions { get; set; }
        public virtual LookupRaceSubTypes LookupRaceSubTypes { get; set; }
        public virtual LookupRacetracks LookupRacetracks { get; set; }
        public virtual Prizes Prizes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaceClaims> RaceClaims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaceResults> RaceResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaceStartPosition> RaceStartPosition { get; set; }
    }
}
