//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtCQRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RacetrackPenalties
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RacetrackPenalties()
        {
            this.RaceResults = new HashSet<RaceResults>();
        }
    
        public int Id { get; set; }
        public Nullable<int> HorsePenaltyId { get; set; }
        public Nullable<int> RiderPenaltyId { get; set; }
        public Nullable<System.DateTime> RiderBanFinishDate { get; set; }
    
        public virtual LookupRacePenalties LookupRacePenalties { get; set; }
        public virtual LookupRacePenalties LookupRacePenalties1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaceResults> RaceResults { get; set; }
    }
}
