//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtCQRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Riders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Riders()
        {
            this.HorseFrisknessRecord = new HashSet<HorseFrisknessRecord>();
            this.HorseRacetrackStats = new HashSet<HorseRacetrackStats>();
            this.RaceClaims = new HashSet<RaceClaims>();
            this.RaceClaims1 = new HashSet<RaceClaims>();
            this.RaceGitResults = new HashSet<RaceGitResults>();
            this.RaceResults = new HashSet<RaceResults>();
            this.RacetrackUsers = new HashSet<RacetrackUsers>();
            this.LookupRiderPositions = new HashSet<LookupRiderPositions>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Addrress { get; set; }
        public string Phone { get; set; }
        public string LicenseNumber { get; set; }
        public string SuitColor { get; set; }
        public string CoachDepartmant { get; set; }
        public bool IsRider { get; set; }
        public bool IsJockey { get; set; }
        public bool IsCoach { get; set; }
        public Nullable<int> RacetrackId { get; set; }
        public Nullable<int> RiderCategoryId { get; set; }
        public string OldSystemId { get; set; }
        public string OldSystemId2 { get; set; }
        public string VniikId { get; set; }
        public System.DateTime BirthDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorseFrisknessRecord> HorseFrisknessRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorseRacetrackStats> HorseRacetrackStats { get; set; }
        public virtual LookupRacetracks LookupRacetracks { get; set; }
        public virtual LookupRiderCategories LookupRiderCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaceClaims> RaceClaims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaceClaims> RaceClaims1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaceGitResults> RaceGitResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaceResults> RaceResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RacetrackUsers> RacetrackUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LookupRiderPositions> LookupRiderPositions { get; set; }
    }
}
