//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtCQRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uploads
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uploads()
        {
            this.HorseImages = new HashSet<HorseImages>();
        }
    
        public int Id { get; set; }
        public string FileType { get; set; }
        public string Description { get; set; }
        public string Filename { get; set; }
        public Nullable<int> LinkedPostId { get; set; }
        public Nullable<int> LinkedDocId { get; set; }
        public Nullable<int> LinkedHorseId { get; set; }
        public Nullable<int> LinkedRacetrackId { get; set; }
        public string OldSystemId { get; set; }
        public string OldSystemId2 { get; set; }
        public string VniikId { get; set; }
        public string Folder { get; set; }
    
        public virtual Documents Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorseImages> HorseImages { get; set; }
        public virtual Horses Horses { get; set; }
        public virtual LookupRacetracks LookupRacetracks { get; set; }
        public virtual Posts Posts { get; set; }
    }
}
